### PR TITLE
[fix] set log dep version as 0.4.21

### PR DESCRIPTION
**Pull request by hky1999**

### CODE REVIEW

**Comment by aarkegz** [comment]
Why don't we fix it at `0.4.21`?

**Comment by hky1999** [comment]
> Why don't we fix it at `0.4.21`?

I fix it as `0.4.21` in `axvm`, I believe that it will cause axdevice to use a `0.4.21` version.

for generality consideration

**Comment by aarkegz** [comment]
> > Why don't we fix it at `0.4.21`?
> 
> I fix it as `0.4.21` in `axvm`, I believe that it will cause axdevice to use a `0.4.21` version.
> 
> for generality consideration

OK. I think that's OK because axdevice it self won't trigger `log`'s bug.

**Review by aarkegz — APPROVED** [review]
LGTM

**Pull request merged**
